### ISSUE TITLE
Panic when respawning a chunk with collisions

### ISSUE THREAD

**Issue by Imakoala** [joshuajbouw/bevy_tilemap#123]
**Bevy Tilemap version**

Git master

**Operating system & version**

Ubuntu 20.04
Note : I have a slightly modified version of bevy_tilemap, it should not have any impact on this bug.
Edit : tested on master, same issue. 

**What you did**

It seems that respawning a chunk with collisions that was previously despawned (using the auto_spawn feature) panics with 
`thread 'main' panicked at 'called 'Result::unwrap()' on an 'Err' value: NoSuchEntity', /home/timo/.cargo/registry/src/github.com-1ecc6299db9ec823/bevy_transform-0.4.0/src/hierarchy/child_builder.rs:65:22`

The panic seem to be in the push_children command, probably the one used in spawn_collisions, where the chunk entity doesn't exist.

I tried to force the collision system to run after the tilemap system, it did not fix it.
Here is a slightly modified version of the physics_dungeon example where the bug can be seen. You just have to go far in one direction then come back for the crash to happen.
[physics_dungeon.txt](https://github.com/joshuajbouw/bevy_tilemap/files/5911501/physics_dungeon.txt)

**Comment by joshuajbouw** [comment]
Thanks, I need to build an example where I can replicate this and can get around to it.

**Comment by Imakoala** [comment]
I started to try to understand the code to fix it this morning, and I have a possible fix / behavior change which incidentally avoid the problem. 

I found another issue while testing, where the collision tile positions are wrong on chunks other than 0,0, due to the fact that their transform is offset and then they are parented to the chunk which adds the offset again.

I tried to solve it by removing the offset, and the rapier debug meshes spawned in the right place, but somehow the collisions were still wrong (maybe rapier doesn't play nicely with parenting ?)

So instead, I suggest the collisions are parented to the tilemap directly (that works on my fork, and fix this issue and the offset problem I just mentioned). 
The collision tiles will have to be manually despawned when a chunk is despawned however. I will add this and then make a PR.

**Comment by joshuajbouw** [comment]
Closed with #124
