### ISSUE TITLE
Support 3D

### ISSUE THREAD

**Issue by lwansbrough** [joshuajbouw/bevy_tilemap#13]
**What problem does this solve or what need does it fill?**

Would be great to be able to use this library for procedurally generated 3D worlds.

**Describe the solution would you like?**

Same easy to use API, but 3D :)

**Comment by joshuajbouw** [comment]
I think this might be out of scope for this project but, I'll leave it open for discussion. Usually tile maps just have orthogonal and isometric viewpoints.

**Comment by huhlig** [comment]
I would be very interested in this. I am working on a prototype at the moment for a game that has 3d buildings and being able to intelligently layer buildings in 3d would be excellent.

**Comment by joshuajbouw** [comment]
Oh I have an update on this, it already exists in master :D. I need to create examples for it though. There were other large improvements, such as a single 3D mesh being used for every layer, and every Z level.

When you are talking "3D" though, as in actual 3D objects, you -should- be able to use 3D characters in the environment, provided you add enough space between Z layers.

**Comment by huhlig** [comment]
I was thinking two different kinds of "3D" layering. First is having tiles both above and below a given Z Layer. I.E 

An Example would be :
* Z0+0.2 - Floor Tiles (Dense)
* Z0+0.4 - Decal Tiles (Sparse)
* Z0+0.6 - Sprite Layer (Empty) 
* Z0+0.8 - Overhead Tiles (Sparse) [Things like animated fans, girders, etc]

Second aspect would be having multiple floors visible at once. Think of a true top down game with a perspective camera akin to the original GTA taking place in a 4 story hotel with a glass floor over the lobby, if you walk around the floor then you would see the lobby several floors down.

**Comment by joshuajbouw** [comment]
Yes, master has this feature :)
