### ISSUE TITLE
Minimap support?

### ISSUE THREAD

**Issue by mattdm** [joshuajbouw/bevy_tilemap#142]
**What problem does this solve or what need does it fill?**

Showing a minimap view with more context (but possibly simplified textures, or simply blocks instead of textured tiles) is pretty common in games. It'd be nice for this library to automatically support it.

**Describe the solution would you like?**

Ability to present a minimap

* of arbitrary pixel dimenisions
* mapped to a greater extent than displayed on screen
* chunks updated in this area, of course
* option for alternate texture atlas for mini versions 

**Describe the alternative(s) you've considered?**

Could be done separately, but it seems like deep integration is actually really useful here

**Comment by joshuajbouw** [comment]
I do not believe that the tilemap should handle this. This can easily be done with a 2nd mini-tilemap which shows colors based on the average tile in a location. It is completely out of scope for this library though.

**Comment by mattdm** [comment]
That's cool; thanks for considering.
