### ISSUE TITLE
Eliminate separate examples crate

### ISSUE THREAD

**Issue by Aposhian** [joshuajbouw/bevy_tilemap#174]
**What problem does this solve or what need does it fill?**
The `examples` crate notes that being a separate crate was a constraint of using Bevy 0.4. Now that we are on Bevy 0.5, can we move the examples into the standard location so you can run `cargo run --example` at the repository root?

**Describe the solution would you like?**
Eliminate `examples` crate and add examples to top level `Cargo.toml`

**Describe the alternative(s) you've considered?**
N/A

**Additional context**
N/A

**Comment by joshuajbouw** [comment]
This has been fixed by #182
