### ISSUE TITLE
Chunks don't line up when using hex grid

### ISSUE THREAD

**Issue by pavlukivan** [joshuajbouw/bevy_tilemap#71]
With `HexX`: ![image](https://user-images.githubusercontent.com/9590981/103167975-4960af00-4862-11eb-99c1-97f433a3b815.png)

With `HexEvenCols`: 
![image](https://user-images.githubusercontent.com/9590981/103167997-65fce700-4862-11eb-96c2-66599c34d918.png)

**Comment by joshuajbouw** [comment]
... Huh. Well that is odd. Not sure if thats a post 0.4 Bevy thing or something else entirely. I'll dig into it.

**Comment by pavlukivan** [comment]
yes, latest commit

**Comment by jamadazi** [comment]
When hexagon grid support was added, we never tested it with multiple chunks, which explains the above problem with the chunk/global positioning.

To fix this, the chunk's translation should be scaled by 3/4 along the axis corresponding to the "pointy side" of the hexagon: that would be X for `HexX`/`Hex*Cols` (as in the screenshots in this issue), and Y for `HexY`/`Hex*Rows`.

**Comment by joshuajbouw** [comment]
Ah yeah, that makes sense. Unfortunately late here and still had family around. I'll get through it from the morning.

**Comment by pavlukivan** [comment]
each chunk also has to have more Y offset with HexX

**Comment by jamadazi** [comment]
Ah yes, that offset along Y (or X for HexY) should be half the tile height (width for HexY) times the number of columns (rows for HexY).
