### ISSUE TITLE
Background stopped updating on examples

### ISSUE THREAD

**Issue by joshuajbouw** [joshuajbouw/bevy_tilemap#74]
**Bevy version**

Master

**Operating system & version**

Windows 10

**What you did**

Ran the examples to see how they are with latest Bevy 0.4 release. Background is failing to render when moving the character.

**What you expected to happen**

For the background to correctly render under the dwarves.

**What actually happened**

The background didn't render.

**Comment by mrhatman** [comment]
I think these are some screen shoots of the issue. It appears to be an alpha issue.

Master
![image](https://user-images.githubusercontent.com/13708510/103372655-2d465300-4a98-11eb-84ce-f24f6d9ce248.png)

v0.2.2
![image](https://user-images.githubusercontent.com/13708510/103372671-3c2d0580-4a98-11eb-82ed-f324f064fda4.png)

**Comment by mrhatman** [comment]
I think  the issue is that you need a way to pass visibility when making the tilemap here:

https://github.com/mrhatman/bevy_tilemap/blob/b0a5b0b918d42a6404171d3732fb6afddbaf7642/src/tilemap.rs#L1896

**Comment by joshuajbouw** [comment]
Thanks for posting the example. Yeah, I need to get down and fix it. It was fine up until the point of Bevy 0.4 release.

**Comment by joshuajbouw** [comment]
Fixed here: https://github.com/joshuajbouw/bevy_tilemap/pull/77
