### ISSUE TITLE
Control over texture filtering mode? Mipmap support?

### ISSUE THREAD

**Issue by jamadazi** [joshuajbouw/bevy_tilemap#76]
I want to have nice quality downscaling, to support "zooming out" the camera (increasing the scale). The current rendering looks ugly (looks like the filtering is probably nearest neighbor with no mipmaps). I want to have control over this, so that my tilemaps can look nice when scaled down.

**Comment by joshuajbouw** [comment]
Oooh this would be sweet. I too need zooming in and out and noticed how ugly it is as well. I'll look into this for a future version.

**Comment by joshuajbouw** [comment]
Second thought, I'd imagine that Bevy itself should fix this with the renderer, unless someone can come up with ideas.

**Comment by joshuajbouw** [comment]
Going to close this as it is out of scope.
